// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"KRD_MZ_Dice","status":true,"description":"サイコロを振り、結果を変数に入れます。","parameters":{"swRolling":"1","varDice":"6","plusX":"0","plusY":"0"}},
{"name":"AltMenuScreen","status":true,"description":"Alternative menu screen layout.","parameters":{}},
{"name":"AltSaveScreen","status":true,"description":"Alternative save/load screen layout.","parameters":{}},
{"name":"ButtonPicture","status":true,"description":"Makes a picture clickable.","parameters":{}},
{"name":"TextPicture","status":true,"description":"Displays text as a picture.","parameters":{}}
];
